### ISSUE TITLE
Testing CloudKibo URL Feb 17 2016

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/Intern#14]
@ImranBinShoukat 

Please test this: 

![image](https://cloud.githubusercontent.com/assets/5336012/13099945/a55fb312-d4ec-11e5-9c64-a055b767a213.png)

**Comment by jekram** [comment]
I am not only looking for functional test and making sure we have quality.

**Comment by sojharo** [comment]
Please test on separate machines

**Comment by ImranBinShoukat** [comment]
We have tested the both webmeeting and conference. But only 2 people test have been tested because of the two machines. We will test with 3 & 4 people tomorrow in the lab. Here are the results.

![17 feb test](https://cloud.githubusercontent.com/assets/17005430/13121446/23c63932-d5d4-11e5-93e3-d49ce0a2c1aa.JPG)

**Comment by ImranBinShoukat** [comment]
![18 feb](https://cloud.githubusercontent.com/assets/17005430/13156983/286da51e-d6a7-11e5-8832-1b275074e5a8.JPG)

**Comment by jekram** [comment]
@ImranBinShoukat 

Thanks for the update. Can you please complete rest of the test also

**Comment by ImranBinShoukat** [comment]
![19 feb](https://cloud.githubusercontent.com/assets/17005430/13182632/81e0b5c0-d754-11e5-85f8-1171ae806f98.JPG)

**Comment by jekram** [comment]
Thanks @ImranBinShoukat
