### ISSUE TITLE
Learn Proto.IO 

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/Intern#21]
@ImranBinShoukat 

Doing a great UI design is a very critical element. So as part of your training, I would like you to learn Proto.IO and do 
[Mock-up from HotLine.pptx](https://github.com/Cloudkibo/Intern/files/185660/Mock-up.from.HotLine.pptx)
 

You can signup for a free trial account at www.proto.io. 

Next steps:

1. They have lots of training video that you should watch.
2. Develop sample apps from tutorials
[Mock-up from HotLine.pptx](https://github.com/Cloudkibo/Intern/files/185670/Mock-up.from.HotLine.pptx)

3. Next, you should develop as a prototype the attached 

Deliverables:

1. Sample from Tutorial
2. Mockup from step three above

Let's target to finish this 31st of March.

**Comment by ImranBinShoukat** [comment]
Today, I watched some of the videos at proto.io

**Comment by ImranBinShoukat** [comment]
Today, I watched some more videos and read the documentation. Also I built the following prototypes.

https://imranshoukat.proto.io/player/index.cfm?id=b4e940ac-1949-458f-9e2e-7406e158df40

https://imranshoukat.proto.io/player/index.cfm?id=a91e78c8-ca83-4059-8543-742a4c0ee61b

**Comment by jekram** [comment]
Thanks.

**Comment by ImranBinShoukat** [comment]
I have watched the 75% of the videos and understood the implementation and functionality of the proto.io.

**Comment by jekram** [comment]
Thanks for the update.

**Comment by jekram** [comment]
@ImranBinShoukat 

Thanks for the update.  What will be the ETA for:

"Deliverables:

Sample from Tutorial
Mockup from step three above
Let's target to finish this 31st of March."

So I can assign next task?

**Comment by jekram** [comment]
@ImranBinShoukat 
I have not seen any update here. What is the status

**Comment by jekram** [comment]
@ImranBinShoukat 

What is the update here? Do you not think you should update on the status.

Copy @sojharo

**Comment by ImranBinShoukat** [comment]
I am really sorry for the lack of communication. However, I have watched all the tutorials of proto.io and here are the samples from tutorial. I posted the link of these sample before as well but since they are not working (sorry for this also) so I made them again. Here are the links:

Pandora
https://imranshoukat1.proto.io/share/?id=0a05f7c0-bb1f-4b93-9f38-8e4bde5b64e2&v=1

Tumblr
https://imranshoukat1.proto.io/share/?id=969e73ad-d878-4257-8f05-f1232b731444&v=1

There were 8 samples but I am not able to make the rest of the samples due to unavailability of their assets. However, I watched the videos and understood the functionality.

I have also made the prototype of Mockup. The link is:
https://imranshoukat1.proto.io/share/?id=55c48494-1180-4ecd-87b9-f4a0598be584&v=1

**Comment by jekram** [comment]
@ImranBinShoukat 

Thanks for the update.

**Comment by jekram** [comment]
@ImranBinShoukat 

Are we done with this task and should we close this please let me know?

**Comment by ImranBinShoukat** [comment]
Yes, you can close this task.

**Comment by jekram** [comment]
Great. I will close this. Normally when a task is done, please make it resolved and I will close it after review.

Great job and thanks.

**Comment by ImranBinShoukat** [comment]
Alright. I'll do this from now on wards.
