### ISSUE TITLE
Learn React Native

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/Intern#23]
@ImranBinShoukat 

As a next step I would like you to learn React Native. React Native allows you to develop mobile applications on iOS and Android. React Native is from Facebook and is a very wonderful tool.

1. Here is the Website:  https://facebook.github.io/react/

Also, watch Videos on Youtube.

2. There is a Tutorial on React  Native on Udemy:  Building Apps with React Native

https://drive.google.com/drive/folders/0ByXJY8WVZm-NaFlBLTJXX2xqejQ

3. Here is a book on React Native.
https://drive.google.com/drive/folders/0ByXJY8WVZm-NZzRpQUI4d2NxX00

Deliverable:

Do all the sample examples on Udemy and in the book.

Target completion is April 15th or sooner.

**Comment by jekram** [comment]
@ImranBinShoukat 

I am going to block this task. I think it would be more prudent for you to learn the basic of ReactJS first before getting confused on React Native.

I will open a new task on ReactJS.

Copying @sojharo

**Comment by ImranBinShoukat** [comment]
Update:
Course — 27% completed
Book — Chapter 1 has been read

**Comment by jekram** [comment]
Thanks for thebupdate

**Comment by ImranBinShoukat** [comment]
Today, I read the chapter 02 and 03 of the 'React Native' book and did some practice.

**Comment by jekram** [comment]
Good

**Comment by ImranBinShoukat** [comment]
Today, I build the first react-native android app but when I tried to run it on Android Studio, it didn't run and gave some errors. With the help of @sojharo I managed to remove some of them but didn't succeed to run the app.
Actually, at first I tried to use BlueStacks instead of "Genymotion or Google emulator", which worked when I create the 'Hello Word' inside the Android Studio but when I tried to import the react-native app then it gave the errors. I managed to remove some of them but it didn't work.
Then I install the Genymotion and add the Virtual device in it but when I tried to start it, it also gave the error.
I'll try to remove these errors on Sunday.

**Comment by jekram** [comment]
Thanks for the update.

**Comment by ImranBinShoukat** [comment]
Task Update:
Built another app today and completed the 47% of tutorials. 
Also read the Chapter 4 of the book.

**Comment by jekram** [comment]
@ImranBinShoukat 

Thanks for the update. 

Let's try to wrap this up in the next 7 days.

**Comment by ImranBinShoukat** [comment]
Today, I did some testing with @sojharo and then completed the 67% of the video tutorials.

**Comment by jekram** [comment]
Thanks.

**Comment by ImranBinShoukat** [comment]
Today, I completed the video tutorials and read the chapter 07 of the book. Also I built one more app today.

**Comment by jekram** [comment]
Thanks for the update

**Comment by ImranBinShoukat** [comment]
Today, I read the remaining chapters of the book and did some practice.

**Comment by jekram** [comment]
Thanks
